THEME = {
    "name": "dark",
    "bg": "#0B0F17",
    "fg": "#E5E7EB",
    "muted": "#9CA3AF",
    "btn_bg": "#1F2937",
    "btn_fg": "#E5E7EB",
    "entry_bg": "#111827",
    "entry_fg": "#E5E7EB",
    "text_bg": "#0F172A",
    "text_fg": "#E5E7EB",
    "text_sel_bg": "#2563EB",
    "text_sel_fg": "#FFFFFF",
    "tv_bg": "#0F172A",
    "tv_fg": "#E5E7EB",
    "tv_header_bg": "#1F2937",
    "tv_header_fg": "#E5E7EB",
    "tv_sel_bg": "#374151",
    "tv_sel_fg": "#E5E7EB",
    "hl_bg": "#7C3AED",
    "hl_fg": "#FFFFFF",
    "font_family": "SF Pro Text",
    "font_size": 12,
}
